-- MySQL Script generated by MySQL Workbench
-- dim. 24 mai 2015 18:25:12 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `nom_local` VARCHAR(45) NULL,
  PRIMARY KEY (`id_local`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Routeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Routeur` (
  `id_routeur` INT NOT NULL AUTO_INCREMENT,
  `id_salle` INT NULL,
  `nom_routeur` VARCHAR(45) NULL,
  `id_local` INT NULL,
  PRIMARY KEY (`id_routeur`),
  INDEX `fk_Routeur_1_idx` (`id_salle` ASC),
  INDEX `fk_Routeur_2_idx` (`id_local` ASC),
  CONSTRAINT `fk_Routeur_1`
    FOREIGN KEY (`id_salle`)
    REFERENCES `mydb`.`Salle` (`id_salle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Routeur_2`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`Local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Switch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Switch` (
  `id_switch` INT NOT NULL AUTO_INCREMENT,
  `id_routeur` INT NULL,
  `id_salle` INT NULL,
  `nom_switch` VARCHAR(45) NULL,
  `id_local` INT NULL,
  PRIMARY KEY (`id_switch`),
  INDEX `fk_Switch_1_idx` (`id_routeur` ASC),
  INDEX `fk_Switch_2_idx` (`id_salle` ASC),
  INDEX `fk_Switch_3_idx` (`id_local` ASC),
  CONSTRAINT `fk_Switch_1`
    FOREIGN KEY (`id_routeur`)
    REFERENCES `mydb`.`Routeur` (`id_routeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Switch_2`
    FOREIGN KEY (`id_salle`)
    REFERENCES `mydb`.`Salle` (`id_salle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Switch_3`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`Local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salle` (
  `id_salle` INT NOT NULL AUTO_INCREMENT,
  `id_local` INT NULL,
  `id_routeur` INT NULL,
  `id_switch` INT NULL,
  `nom_salle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_salle`),
  INDEX `fk_Salle_1_idx` (`id_local` ASC),
  INDEX `fk_Salle_2_idx` (`id_routeur` ASC),
  INDEX `fk_Salle_3_idx` (`id_switch` ASC),
  CONSTRAINT `fk_Salle_1`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`Local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salle_2`
    FOREIGN KEY (`id_routeur`)
    REFERENCES `mydb`.`Routeur` (`id_routeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salle_3`
    FOREIGN KEY (`id_switch`)
    REFERENCES `mydb`.`Switch` (`id_switch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordinateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordinateur` (
  `id_ordinateur` INT NOT NULL AUTO_INCREMENT,
  `id_salle` INT NULL,
  `id_switch` INT NULL,
  `nom_ordinateur` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ordinateur`),
  CONSTRAINT `fk_Ordinateur_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Salle` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordinateur_2`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Switch` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carte_reseau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carte_reseau` (
  `id_carte_reseau` INT NOT NULL AUTO_INCREMENT,
  `id_ordinateur` INT NULL,
  `id_routeur` INT NULL,
  `adresse_mac` VARCHAR(45) NULL,
  PRIMARY KEY (`id_carte_reseau`),
  INDEX `fk_Carte_reseau_2_idx` (`id_routeur` ASC),
  CONSTRAINT `fk_Carte_reseau_1`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Ordinateur` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carte_reseau_2`
    FOREIGN KEY (`id_routeur`)
    REFERENCES `mydb`.`Routeur` (`id_routeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- INSERT DE TEST
-- -----------------------------------------------------
SET foreign_key_checks = 0;

INSERT INTO 


SET foreign_key_checks = 1;
